language: python
python: 3
dist: xenial

before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run flake8
- poetry run pytest
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
